accounts/urls.py
from django.urls import path, re_path

from . import views

from django.contrib.auth.views import (
    login, logout, 
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete,
)

app_name = "accounts"
urlpatterns = [
   path('',views.dashboard, name="home"),
   path('login/',login,{'template_name':'accounts/index.html'}),
   path('logout/',logout,{'template_name':'accounts/logout.html'}),
   # path('logout/',views.logout_view, name="logout"),
   path('register/',views.registration,name="register"),
   path('sentiment/<int:primary_id>',views.sentiment, name='sentiment'),
   path('attachments/<int:primary_id>',views.attachments, name="attachments"),
   path('results/<int:primary_id>',views.data_processing, name='analysis')
]

business/urls.py
from django.contrib import admin
from django.urls import path,include
from business import views

urlpatterns = [
    path('', views.login_redirect, name="login_redirect"),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save,post_save
from django.utils import timezone

# Create your models here.
class FileUploads(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=50, default = '')
	file = models.FileField(upload_to='media/')
	content = models.TextField()
	summary = models.CharField(max_length = 150, default = '')
	created_at = models.DateTimeField(auto_now=True)

	

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
		UserCreationForm
	)

from django.forms import ModelForm, Textarea,HiddenInput
from accounts.models import FileUploads

class AddUsersForm(UserCreationForm):
	email = forms.EmailField(required = False)
	class Meta:
		model = User
		fields = (
			'username',
			'email',
			'password1',
			'password2'
			)

	def save(self,commit = False):
		user = super(AddUsersForm, self).save(commit=False)
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class UploadFileForm(forms.ModelForm):
	class Meta:
		model = FileUploads
		fields = (
			'title',
			'file',
			'summary'
			)
		widgets = {
			'summary':Textarea(attrs={"class":"materialize_textarea","data-length":"150"}),
		}

accounts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from accounts.forms import (
	AddUsersForm,
	UploadFileForm
	)
from django.contrib.auth import authenticate,login,update_session_auth_hash,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from accounts.models import FileUploads


# importing the NLP toolkits
import os
from nltk.tokenize import (
		sent_tokenize,
		word_tokenize
	)
from nltk import pos_tag
from nltk.corpus import stopwords
from textalyzer import Textalyzer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Create your views here.

@login_required
def login_auth(request):
	username = request.POST['username']
	password = request.POST['password1']
	user = authenticate(username = username, password = password)
	if user is not None and user.is_authenticated:
		login(request,user)
		return redirect('accounts/dashboard.html')

def registration(request):
	if request.method == 'POST':
	    form = AddUsersForm(request.POST)
	    if form.is_valid():
	    	instance = form.save(commit=False)
	    	instance.save()
	    	username = form.cleaned_data.get("username")
	    	raw_password = form.cleaned_data.get("password1")
	    	user = authenticate(username=username, password=raw_password)
	    	login(request, user)
	    	return redirect('/accounts')
	else:
		form = AddUsersForm()
		context = {
			'form':form
		}
		return render(request, 'accounts/register.html',context)
   


@login_required
def dashboard(request):
	context = {
		'form':"banks"
	}
	return render(request,'accounts/dashboard.html',context)


@login_required
def sentiment(request,primary_id):
	if request.method == 'POST':
		form = UploadFileForm(request.POST or None, request.FILES or None)
		get_id = primary_id
		if form.is_valid():
			content = request.FILES['file']
			if content.multiple_chunks():
				print("Uploaded file is too big (%.2f MB)" % (content.size/(1000*1000),))
			
			file_data = content.read()
			instance = form.save(commit=False)
			instance.user_id = get_id
			instance.content = file_data
			instance.save()
			return redirect('/accounts')
	else:
		form = UploadFileForm()
		context = {
			'upload_form':form
		}
		return render(request,'accounts/sentiment_form.html',context)

@login_required
def attachments(request,primary_id):
	all_attachments = FileUploads.objects.filter(user_id=primary_id)
	all_att_counts = all_attachments.count()
	
	context = {
		'counts':all_att_counts,
		'all_attachments':all_attachments
	}
	return render(request,'accounts/attachments.html',context)

@login_required
def data_processing(request,primary_id):
	file_content = ''
	get_attachment = FileUploads.objects.get(id=primary_id)
	file_data = get_attachment.content

	# Tokenization starts here
	sentence = sent_tokenize(file_data)
	words = word_tokenize(str(sentence))

	#Removing punctuation and other stuff
	punct_free = [word for word in words if word.isalpha()]
	stop_words = [word for word in punct_free if word not in stopwords.words('english')]

	# Processing starts from here
	replacers = Textalyzer.RegexpReplacer()

	# removing unwanted data
	stripped_data = replacers.replace(str(stop_words))
	# This is the fun part
	sid = SentimentIntensityAnalyzer()
	sdata = sid.polarity_scores(stripped_data)

	positivity = sdata['pos']
	negativity = sdata['neg']
	neutrality = sdata['neu']

	compound   = sdata['compound']
	
	context = {
		"positivity":positivity,
		"negativity":negativity,
		"neutrality":neutrality,
		"compound":compound
	}
	return render(request,'accounts/results.html',context)

business/views.py
from django.shortcuts import redirect
def login_redirect(request):
	return redirect('/accounts/login')

accounts/templates/accounts/attachments.html
{% extends "accounts/base/base.html" %}

{% block navbar %}
	{% include "accounts/base/_navbar.html" %}
{% endblock navbar %}

{% block content %}
	<main>
		<div class="row">
			<div class="col s2 m2 l2" id="side-navigation">
				{% include "accounts/base/sidenav.html" %}
			</div>
			<div class="col s8 m8 l8 offset-s1 offset-m1 offset-l1">
				{% if counts > 0 %}
					{% for files in all_attachments %}
					<div class="col s4 m4 l4">
						<form method="post" action="/accounts/results/{{ files.id }}">
							{% csrf_token %}
							<div class="col s12 m12 l12 card-panel z-depth-2" style="padding: 10px;">
								<div class="col s2 m2 l2">
									{% load static %}
									<img src="{% static 'accounts/images/papers.svg' %}" alt=" {{ files.title }}" style="width: 40px;height: 40px;">
									
								</div>
								<div class="col s10 m10 l10">
									<h5 style="font-size: 18px;font-weight: bold;padding-left: 5px;margin-top: -3px;">{{ files.title }}</h5>
									<p style="text-align: justify;padding-left: 5px;font-size: 15px;font-weight: bold;line-height: 1.2;">{{ files.summary | truncatechars:120 }}</p>
								</div>
							</div>
							<div class="col s12 m12 l12 card-panel z-depth-2" style="margin-top: -20px;">
								<button type="submit" class="btn-flat small right" style="font-size: 13px;text-transform: capitalize;font-weight: bold;margin: 4px;">Analyze</button>
							</div>
						</form>
					</div>
					{% endfor %}
				{% else %}

				{% endif %}
			</div>
		</div>
	</main>
{% endblock content %}

accounts/templates/accounts/base/_navbar.html
<div class="navbar-fixed">
	<nav class="nav-wrapper  red darken-4 z-depth-2" id="navigator">
		<a href="/accounts/{{ user.id }}" class="brand-logo" style="margin-left: 23px;">SentAI</a>
		<ul id="nav-demo" class="right hide-on-med-and-down">
			<!-- <li>
				<a href="index"><i class="material-icons left">home</i>Home</a>
			</li>
			<li>
				<a href="index"><i class="material-icons left">loyalty</i>About</a>
			</li>
			<li>
				<a href="index"><i class="material-icons left">phone</i>Contact</a>
			</li>
			<li>
				<a href="index"><i class="material-icons left">event</i>Events</a>
			</li> -->
			<li>
				<a href="/accounts/logout"><i class="material-icons left">power_settings_new</i></a>
			</li>
		</ul>
	</nav>
</div>

accounts/templates/accounts/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} Sentiment Analytica {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static 'accounts/css/materialize.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'accounts/css/styles.css' %}"/>
</head>
<body>
	{% block navbar %}
	{% endblock %}
	
	{% block content %}
	{% endblock %}
	<script src="{% static 'accounts/js/jquery.js'%}"></script>
	<script src="{% static 'accounts/js/materialize.min.js' %}"></script>
	<script src="{% static 'accounts/js/moment.js' %}"></script>
	<script src="{% static 'accounts/js/lodash.js' %}"></script>

</body>
</html>

accounts/templates/accounts/base/navbar.html
<div class="navbar-fixed">
	<nav class="nav-wrapper  red darken-4 z-depth-0" id="navigator">
		<a href="{% url 'accounts:home' %}" class="brand-logo" style="margin-left: 23px;">BI</a>
		<ul id="nav-demo" class="right hide-on-med-and-down">
			<!-- <li>
				<a href="index"><i class="material-icons left">home</i>Home</a>
			</li>
			<li>
				<a href="index"><i class="material-icons left">loyalty</i>About</a>
			</li>
			<li>
				<a href="index"><i class="material-icons left">phone</i>Contact</a>
			</li>-->
			<li>
				<a href="/accounts/login"><i class="material-icons left">loyalty</i>Sign In</a>
			</li> 
			<li>
				<a href="{% url 'accounts:register' %}"><i class="material-icons left">person_add</i>Register Now</a>
			</li>
		</ul>
	</nav>
</div>

accounts/templates/accounts/base/sidenav.html
<div class="navigation z-depth-0" style="border-right: 1px solid #e8e8e8;margin-left: -15px;z-index: 10;margin-top:2px;">
	<ul class="nav-demo">
		<li id="home" style="margin-right: -6px;">
			<a href="{% url 'accounts:home' %}">
				<i class="material-icons left icon">dashboard</i>
				<span class="menu_name">Dashboard</span>
			</a>
		</li>
		<li id="home" style="margin-right: -6px;">
			<a href="/accounts/attachments/{{ user.id }}">
				<i class="material-icons left icon">attachment</i>
				<span class="menu_name">Files</span>
			</a>
		</li>
		<li id="home" style="margin-right: -6px;">
			<a href="">
				<i class="material-icons left icon">star</i>
				<span class="menu_name">Starred Files</span>
			</a>
		</li>

	   <div class="divider"></div>
        <li class="grey-text text-accent-1 header disabled">Analysis</li>
		<li style="margin-right: -6px;">
			<a href="/accounts/sentiment/{{ user.id }}">
				<i class="material-icons left icon">pie_chart</i>
				<span class="menu_name">Sentiment </span>
			</a>
		</li>

		<li style="margin-right: -6px;">
			<a href="admin/reports">
				<i class="material-icons left icon">print</i>
				<span class="menu_name">Text Summarization </span>
			</a>
		</li>


		<div class="divider"></div>
		<li class="grey-text text-accent-1 header disabled">General Settings</li>
		<li style="margin-right: -6px;">
			<a href="admin/edit">
				<i class="material-icons left icon">person_pin</i>
				<span class="menu_name">Edit Profile</span>
			</a>
		</li>

		<li style="margin-right: -6px;">
			<a href="/accounts/logout">
				<i class="material-icons left icon">power_settings_new</i>
				<span class="menu_name">Logout</span>
			</a>
		</li> 

      <!--   <li style="margin-right: -6px;">
            <a href="admin/claims">
                <i class="material-icons left icon">loyalty</i>
                <span class="menu_name">Claim Mgmt</span>
            </a>
        </li>
        <li style="margin-right: -6px;">
            <a href="admin/salaries">
                <i class="material-icons left icon">credit_card</i>
                <span class="menu_name">Salary Details</span>
            </a>
        </li>
        <li style="margin-right: -6px;">
            <a href="admin/travels">
                <i class="material-icons left icon">time_to_leave</i>
                <span class="menu_name">Travel Desk</span>
            </a>
        </li>

        <div class="divider"></div>
        <li class="grey-text text-accent-1 header disabled">Data Analysis</li>
		<li style="margin-right: -6px;">
			<a href="admin/analytics">
				<i class="material-icons left icon">pie_chart</i>
				<span class="menu_name">Analytics </span>
			</a>
		</li>

		<li style="margin-right: -6px;">
			<a href="admin/reports">
				<i class="material-icons left icon">print</i>
				<span class="menu_name">Reports </span>
			</a>
		</li>


		<div class="divider"></div>
		<li class="grey-text text-accent-1 header disabled">General Settings</li>
		<li style="margin-right: -6px;">
			<a href="admin/edit">
				<i class="material-icons left icon">person_pin</i>
				<span class="menu_name">Edit Profile</span>
			</a>
		</li> -->

		<!-- <li style="margin-right: -6px;">
			<a href="admin/password">
				<i class="material-icons left icon">vpn_lock</i>
				<span class="menu_name">Change Password</span>
			</a>
		</li>

        <div class="divider"></div>
        <li class="grey-text text-accent-1 header disabled">Reported Issues</li>
        <li style="margin-right: -6px;">
            <a href="admin/feedback">
                <i class="material-icons left icon">bug_report</i>
                <span class="menu_name">Issues</span>
            </a>
        </li>

        <li style="margin-right: -6px;">
            <a href="admin/feedback">
                <i class="material-icons left icon">flag</i>
                <span class="menu_name">Feedback</span>
            </a>
        </li>

		<li style="margin-right: -6px;">
			<a href="/accounts/logout">
				<i class="material-icons left icon">power_settings_new</i>
				<span class="menu_name">Logout</span>
			</a>
		</li> -->
		
	</ul>
</div>

accounts/templates/accounts/dashboard.html
{% extends "accounts/base/base.html" %}

{% block navbar %}
	{% include "accounts/base/_navbar.html" %}
{% endblock navbar %}

{% block content %}
	<main>
		<div class="row">
			<div class="col s2 m2 l2" id="side-navigation">
				{% include "accounts/base/sidenav.html" %}
			</div>
			<div class="col s8 m8 l8 offset-s1 offset-m1 offset-l1">
				<div class="col s12 m8 l8">
					<div class="col s12 m12 l12 card-panel">
						<canvas id="myChart" width="600" height="400"></canvas>
					</div>
				</div>
				<div class="col s12 m4 l4">
					<div class="col s12 m12 l12 card-panel">
						<div class="info" style="padding: 10px;">
							<p style="font-weight: bold;font-size: 18px;">Username : <span style="font-weight: bold;font-size: 16px;padding-bottom: 10px;">{{ user.username }}</span></p>
						    <div class="divider"></div>
							<p style="font-weight: bold;">Email Address : <span style="font-weight: bold;font-size: 18px;">{{ user.email }}</span></p>
						</div>
						
					</div>
				</div>

			</div>
		</div>
		{% block javascript %}
			<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
				<script>
				var ctx = document.getElementById("myChart");
				var myChart = new Chart(ctx, {
				    type: 'bar',
				    data: {
				        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
				        datasets: [{
				            label: '# of Votes',
				            data: [12, 19, 3, 5, 2, 3],
				            backgroundColor: [
				                'rgba(255, 99, 132, 0.2)',
				                'rgba(54, 162, 235, 0.2)',
				                'rgba(255, 206, 86, 0.2)',
				                'rgba(75, 192, 192, 0.2)',
				                'rgba(153, 102, 255, 0.2)',
				                'rgba(255, 159, 64, 0.2)'
				            ],
				            borderColor: [
				                'rgba(255,99,132,1)',
				                'rgba(54, 162, 235, 1)',
				                'rgba(255, 206, 86, 1)',
				                'rgba(75, 192, 192, 1)',
				                'rgba(153, 102, 255, 1)',
				                'rgba(255, 159, 64, 1)'
				            ],
				            borderWidth: 1
				        }]
				    },
				    options: {
				        scales: {
				            yAxes: [{
				                ticks: {
				                    beginAtZero:true
				                }
				            }]
				        },
				        animation:{
				        	easing:'easeInQuad',
				        	duration:1500
				        }
				    }
				});
				</script>
		{% endblock javascript %}
	</main>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends "accounts/base/base.html" %}

{% block title %} Home | Sentiment Analytica {% endblock %}
{% block navbar %}
	{% include "accounts/base/navbar.html" %}
{% endblock navbar %}

{% block content %}
	<main>
		<div class="row">
			<div class="container">
				<div class="col s12 m6 l6 offset-m3 offset-l3 card-panel" style="padding-top: 20px;padding-bottom: 20px;position: relative;top: 8rem;">
					<form method="post">
					  <div class="col s12 m12 l12">
					  	{% csrf_token %}
					  	{{ form.as_p }}
					  </div>
					  <div class="input-field col s12 m12 l12">
					  	<button type="submit" class="btn waves-effect waves-light">Log In</button>
					  </div>
					</form>
				</div>
			</div>
		</div>
	</main>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "accounts/base/base.html" %}

{% block navbar %}
	{% include "accounts/base/navbar.html" %}
{% endblock navbar %}

{% block content %}
	<main>
		<div class="row">
			<div class="container">
				<div class="col s12 m6 l6 offset-m3 offset-l3 card-panel" style="padding-top: 20px;padding-bottom: 20px;position: relative;top: 2rem;">
					<form method="post">
					  <div class="col s12 m12 l12">
					  	{% csrf_token %}
					  	{{ form.as_p }}
					  </div>
					  <div class="input-field col s12 m12 l12">
					  	<button type="submit" class="btn waves-effect waves-light">Register</button>
					  </div>
					</form>
				</div>
			</div>
		</div>
	</main>
{% endblock content %}

accounts/templates/accounts/results.html
{% extends "accounts/base/base.html" %}

{% block navbar %}
	{% include "accounts/base/_navbar.html" %}
{% endblock navbar %}

{% block content %}
	<main>
		<div class="row">
			<div class="col s2 m2 l2" id="side-navigation">
				{% include "accounts/base/sidenav.html" %}
			</div>
			<div class="col s8 m8 l8 offset-s1 offset-m1 offset-l1">
				<div class="col s12 m8 l8">
					<div class="col s12 m12 l12 card-panel">
						<canvas id="myChart" width="600" height="400"></canvas>
					</div>
				</div>
				<div class="col s12 m4 l4">
					<div class="col s12 m12 l12 card-panel" id="minedChart">
						{% load static %}
						 <script type="text/javascript" src="{% static 'accounts/js/loader.js' %}"></script>
                        <script type="text/javascript">
                            //Codes for the display of the donut chart -visualization
                            google.charts.load("current", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawDonutChart);

                            var mined_pos = {{ positivity }}
                            var mined_neg = {{ negativity }}

                            function drawDonutChart() {
                                var data = google.visualization.arrayToDataTable([
                                    ['Opinions', 'Sentiment Orientation'],
                                    ['Positive', mined_pos],
                                    ['Negative', mined_neg],
                                  
                                ]);

                                var options = {
                                    title: 'User Opinions From External Source',
                                    pieHole: 0.4,
                                    width: 330,
                                    height: 220,
                                };

                                var chart = new google.visualization.PieChart(document.getElementById('minedChart'));
                                chart.draw(data, options);
                            }
                        </script>
                        <!-- <div id="minedChart"  style="margin-left: -30px;"></div> -->
					</div>
				</div>
			</div>
		</div>
		{% block javascript %}
			<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
				<script>
				var ctx = document.getElementById("myChart");
				var myChart = new Chart(ctx, {
				    type: 'bar',
				    data: {
				        labels: ["Positive Sentiment", "Neutral", "Negative Sentiment"],
				        datasets: [{
				            label: 'Sentiment Polarity',
				            data: [{{ positivity  }},{{ neutrality }} , {{ negativity}}],
				            backgroundColor: [
				                'rgba(255, 99, 132, 0.2)',
				                'rgba(54, 162, 235, 0.2)',
				                'rgba(255, 206, 86, 0.2)',
				            ],
				            borderColor: [
				                'rgba(255,99,132,1)',
				                'rgba(54, 162, 235, 1)',
				                'rgba(255, 206, 86, 1)',
				            ],
				            borderWidth: 2
				        }]
				    },
				    options: {
				        scales: {
				            yAxes: [{
				                ticks: {
				                    beginAtZero:true
				                }
				            }]
				        },
				        animation:{
				        	easing:'easeInQuad',
				        	duration:1500
				        }
				    }
				});
				</script>
		{% endblock javascript %}
	</main>
{% endblock content %}

accounts/templates/accounts/sentiment_form.html
{% extends "accounts/base/base.html" %}

{% block navbar %}
	{% include "accounts/base/_navbar.html" %}
{% endblock navbar %}

{% block content %}
	<main>
		<div class="row">
			<div class="col s2 m2 l2" id="side-navigation">
				{% include "accounts/base/sidenav.html" %}
			</div>
			<div class="col s8 m8 l8 offset-s1 offset-m1 offset-l1">
				<div class="container">
					<div class="col s12 m12 l12 card-panel" style="margin-top: 50px;">
						<h5 class="center-align grey-text text-darken-2">Upload File To Analyze</h5>
						<div class="divider"></div>
						<form method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="col s12 m12 12">
							{% for field in upload_form.visible_fields %}
								<input type="hidden" name="id_user" value="{{ user.id }}">
								<div class="input-field">
									{{ field.label }}
									{{ field }}
									{{ field.errors }}
								</div>
							{% endfor %}
							</div>
							<div class="input-field col s12 m12 l12">
								<button type="submit" class="btn red darken-4">Upload</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</main>
{% endblock content %}